### ISSUE TITLE
demo site is incompatible with Django 1.9

### ISSUE THREAD

**Issue by brunobord** [novafloss/django-formidable#144]
steps to reproduce (inside a clean virtualenv, at least):

```
pip install -e ./
pip install -r demo/requirements-demo.pip
cd demo
make
```

Result:

```
python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x2b5a8f46a578>
Traceback (most recent call last):
  File "/home/novapost/.virtualenvs/FORMIDABLE/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/novapost/.virtualenvs/FORMIDABLE/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/novapost/.virtualenvs/FORMIDABLE/local/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/novapost/.virtualenvs/FORMIDABLE/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/novapost/.virtualenvs/FORMIDABLE/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/novapost/.virtualenvs/FORMIDABLE/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 27, in check_resolver
    warnings.extend(check_resolver(pattern))
  File "/home/novapost/.virtualenvs/FORMIDABLE/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 31, in check_resolver
    warnings.extend(check_pattern_startswith_slash(pattern))
  File "/home/novapost/.virtualenvs/FORMIDABLE/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 67, in check_pattern_startswith_slash
    regex_pattern = pattern.regex.pattern
AttributeError: 'str' object has no attribute 'regex'
```

result of pip freeze:

```
Django==1.9.12
Markdown==2.6.7
Pygments==2.1.3
backports.shutil-get-terminal-size==1.0.0
decorator==4.0.10
django-cors-headers==1.3.1
django-extensions==1.7.5
-e git+git@github.com:novafloss/django-formidable.git@abcd1234567890abcd...
djangorestframework==3.5.3
enum34==1.1.6
freezegun==0.3.8
ipdb==0.10.1
ipython==5.1.0
ipython-genutils==0.1.0
pathlib2==2.1.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.9
ptyprocess==0.5.1
python-dateutil==2.6.0
simplegeneric==0.8.1
six==1.10.0
traitlets==4.3.1
wcwidth==0.1.7
```

**Comment by brunobord** [comment]
for some reasons... it's working back again.
